name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI-CD:
    uses: BrunoBrasolin/workflow-template/.github/workflows/angular-gh_pages.yml@main
    with:
      applicationName: front-chat
      cname: chat.gamidas.dev.br
